export enum CategoriaGramatical {
    SUSTANTIVO = 'SUSTANTIVO',
    VERBO = 'VERBO',
    PRONOMBRE = 'PRONOMBRE',
    ADJETIVO = 'ADJETIVO',
    ARTICULO = 'ARTICULO',
    PREPOSICION = 'PREPOSICION',
    CONJUNCION = 'CONJUNCION',
    ADVERBIO = 'ADVERBIO',
    PUNTUACION = 'PUNTUACION',
    DESCONOCIDO = 'DESCONOCIDO'
}

export interface TokenLexico {
    id: number;
    palabra: string;
    categoria: CategoriaGramatical;
    linea: number;
    columna: number;
    valor: string;
}

export const PALABRAS_CLAVE: Record<string, CategoriaGramatical> = {
    'the': CategoriaGramatical.ARTICULO,
    'el': CategoriaGramatical.ARTICULO,
    'la': CategoriaGramatical.ARTICULO,
    'los': CategoriaGramatical.ARTICULO,
    'las': CategoriaGramatical.ARTICULO,
    'a': CategoriaGramatical.ARTICULO,
    'an': CategoriaGramatical.ARTICULO,
    'un': CategoriaGramatical.ARTICULO,
    'una': CategoriaGramatical.ARTICULO,
    'i': CategoriaGramatical.PRONOMBRE,
    'yo': CategoriaGramatical.PRONOMBRE,
    'you': CategoriaGramatical.PRONOMBRE,
    'tú': CategoriaGramatical.PRONOMBRE,
    'tu': CategoriaGramatical.PRONOMBRE,
    'usted': CategoriaGramatical.PRONOMBRE,
    'tus': CategoriaGramatical.PRONOMBRE,
    'mis': CategoriaGramatical.PRONOMBRE,
    'he': CategoriaGramatical.PRONOMBRE,
    'él': CategoriaGramatical.PRONOMBRE,
    'she': CategoriaGramatical.PRONOMBRE,
    'ella': CategoriaGramatical.PRONOMBRE,
    'it': CategoriaGramatical.PRONOMBRE,
    'eso': CategoriaGramatical.PRONOMBRE,
    'we': CategoriaGramatical.PRONOMBRE,
    'nosotros': CategoriaGramatical.PRONOMBRE,
    'they': CategoriaGramatical.PRONOMBRE,
    'ellos': CategoriaGramatical.PRONOMBRE,
    'me': CategoriaGramatical.PRONOMBRE,
    'him': CategoriaGramatical.PRONOMBRE,
    'her': CategoriaGramatical.PRONOMBRE,
    'us': CategoriaGramatical.PRONOMBRE,
    'them': CategoriaGramatical.PRONOMBRE,
    'my': CategoriaGramatical.PRONOMBRE,
    'your': CategoriaGramatical.PRONOMBRE,
    'his': CategoriaGramatical.PRONOMBRE,
    'our': CategoriaGramatical.PRONOMBRE,
    'their': CategoriaGramatical.PRONOMBRE,
    'mi': CategoriaGramatical.PRONOMBRE,
    'su': CategoriaGramatical.PRONOMBRE,
    'nuestro': CategoriaGramatical.PRONOMBRE,
    'nuestra': CategoriaGramatical.PRONOMBRE,
    'in': CategoriaGramatical.PREPOSICION,
    'en': CategoriaGramatical.PREPOSICION,
    'on': CategoriaGramatical.PREPOSICION,
    'sobre': CategoriaGramatical.PREPOSICION,
    'at': CategoriaGramatical.PREPOSICION,
    'with': CategoriaGramatical.PREPOSICION,
    'con': CategoriaGramatical.PREPOSICION,
    'without': CategoriaGramatical.PREPOSICION,
    'sin': CategoriaGramatical.PREPOSICION,
    'for': CategoriaGramatical.PREPOSICION,
    'para': CategoriaGramatical.PREPOSICION,
    'from': CategoriaGramatical.PREPOSICION,
    'de': CategoriaGramatical.PREPOSICION,
    'desde': CategoriaGramatical.PREPOSICION,
    'to': CategoriaGramatical.PREPOSICION,
    'of': CategoriaGramatical.PREPOSICION,
    'by': CategoriaGramatical.PREPOSICION,
    'por': CategoriaGramatical.PREPOSICION,
    'about': CategoriaGramatical.PREPOSICION,
    'into': CategoriaGramatical.PREPOSICION,
    'dentro': CategoriaGramatical.PREPOSICION,
    'over': CategoriaGramatical.PREPOSICION,
    'under': CategoriaGramatical.PREPOSICION,
    'debajo': CategoriaGramatical.PREPOSICION,
    'and': CategoriaGramatical.CONJUNCION,
    'y': CategoriaGramatical.CONJUNCION,
    'or': CategoriaGramatical.CONJUNCION,
    'o': CategoriaGramatical.CONJUNCION,
    'but': CategoriaGramatical.CONJUNCION,
    'pero': CategoriaGramatical.CONJUNCION,
    'because': CategoriaGramatical.CONJUNCION,
    'porque': CategoriaGramatical.CONJUNCION,
    'if': CategoriaGramatical.CONJUNCION,
    'si': CategoriaGramatical.CONJUNCION,
    'when': CategoriaGramatical.CONJUNCION,
    'cuando': CategoriaGramatical.CONJUNCION,
    'while': CategoriaGramatical.CONJUNCION,
    'mientras': CategoriaGramatical.CONJUNCION,
    'although': CategoriaGramatical.CONJUNCION,
    'aunque': CategoriaGramatical.CONJUNCION,
    'that': CategoriaGramatical.CONJUNCION,
    'que': CategoriaGramatical.CONJUNCION,
    'very': CategoriaGramatical.ADVERBIO,
    'muy': CategoriaGramatical.ADVERBIO,
    'quickly': CategoriaGramatical.ADVERBIO,
    'rápidamente': CategoriaGramatical.ADVERBIO,
    'slowly': CategoriaGramatical.ADVERBIO,
    'lentamente': CategoriaGramatical.ADVERBIO,
    'today': CategoriaGramatical.ADVERBIO,
    'hoy': CategoriaGramatical.ADVERBIO,
    'tomorrow': CategoriaGramatical.ADVERBIO,
    'mañana': CategoriaGramatical.ADVERBIO,
    'yesterday': CategoriaGramatical.ADVERBIO,
    'ayer': CategoriaGramatical.ADVERBIO,
    'now': CategoriaGramatical.ADVERBIO,
    'ahora': CategoriaGramatical.ADVERBIO,
    'always': CategoriaGramatical.ADVERBIO,
    'siempre': CategoriaGramatical.ADVERBIO,
    'never': CategoriaGramatical.ADVERBIO,
    'nunca': CategoriaGramatical.ADVERBIO,
    'here': CategoriaGramatical.ADVERBIO,
    'aquí': CategoriaGramatical.ADVERBIO,
    'there': CategoriaGramatical.ADVERBIO,
    'allí': CategoriaGramatical.ADVERBIO,
    'well': CategoriaGramatical.ADVERBIO,
    'bien': CategoriaGramatical.ADVERBIO,
    'also': CategoriaGramatical.ADVERBIO,
    'también': CategoriaGramatical.ADVERBIO,
    'only': CategoriaGramatical.ADVERBIO,
    'solo': CategoriaGramatical.ADVERBIO,
    'just': CategoriaGramatical.ADVERBIO,
    'even': CategoriaGramatical.ADVERBIO,
    'incluso': CategoriaGramatical.ADVERBIO,
    'not': CategoriaGramatical.ADVERBIO,
    'no': CategoriaGramatical.ADVERBIO
};

export const VERBOS_INGLES = [
    'is', 'are', 'am', 'have', 'has', 'eat', 'eats', 'drink', 'drinks',
    'run', 'runs', 'walk', 'walks', 'read', 'reads', 'write', 'writes',
    'sleep', 'sleeps', 'speak', 'speaks', 'listen', 'listens',
    'buy', 'buys', 'sell', 'sells', 'open', 'opens', 'close', 'closes',
    'begin', 'begins', 'finish', 'finishes', 'love', 'loves', 'hate', 'hates',
    'help', 'helps', 'call', 'calls', 'answer', 'answers', 'ask', 'asks',
    'believe', 'believes', 'remember', 'remembers', 'forget', 'forgets',
    'understand', 'understands', 'learn', 'learns', 'teach', 'teaches',
    'show', 'shows', 'tell', 'tells', 'bring', 'brings', 'send', 'sends',
    'receive', 'receives', 'pay', 'pays', 'wait', 'waits', 'need', 'needs',
    'try', 'tries', 'fail', 'fails', 'win', 'wins', 'lose', 'loses',
    'play', 'plays', 'sing', 'sings', 'dance', 'dances', 'cook', 'cooks',
    'clean', 'cleans', 'wash', 'washes', 'drive', 'drives', 'fly', 'flies',
    'swim', 'swims', 'climb', 'climbs', 'fall', 'falls', 'build', 'builds',
    'create', 'creates', 'break', 'breaks', 'fix', 'fixes', 'cut', 'cuts',
    'paint', 'paints', 'draw', 'draws', 'push', 'pushes', 'pull', 'pulls',
    'carry', 'carries', 'throw', 'throws', 'catch', 'catches', 'hit', 'hits',
    'jump', 'jumps', 'sit', 'sits', 'stand', 'stands', 'find', 'finds',
    'search', 'searches', 'save', 'saves', 'delete', 'deletes',
    'download', 'downloads', 'upload', 'uploads', 'install', 'installs',
    'update', 'updates', 'print', 'prints', 'scan', 'scans', 'copy', 'copies',
    'paste', 'pastes', 'chat', 'chats', 'work', 'works', 'study', 'studies',
    'think', 'thinks', 'know', 'knows', 'want', 'wants', 'give', 'gives',
    'take', 'takes', 'see', 'sees', 'come', 'comes', 'look', 'looks',
    'make', 'makes', 'get', 'gets', 'go', 'goes', 'say', 'says',
    'like', 'likes', 'use', 'uses', 'be', 'being'
];

export const VERBOS_ESPANOL = [
    'es', 'son', 'soy', 'tener', 'tiene', 'comer', 'come', 'beber', 'bebe',
    'correr', 'corre', 'caminar', 'camina', 'leer', 'lee', 'escribir', 'escribe',
    'dormir', 'duerme', 'hablar', 'habla', 'escuchar', 'escucha',
    'comprar', 'compra', 'vender', 'vende', 'abrir', 'abre', 'cerrar', 'cierra',
    'empezar', 'empieza', 'terminar', 'termina', 'amar', 'ama', 'odiar', 'odia',
    'ayudar', 'ayuda', 'llamar', 'llama', 'responder', 'responde',
    'preguntar', 'pregunta', 'creer', 'cree', 'recordar', 'recuerda',
    'olvidar', 'olvida', 'entender', 'entiende', 'aprender', 'aprende',
    'enseñar', 'enseña', 'mostrar', 'muestra', 'contar', 'cuenta',
    'traer', 'trae', 'enviar', 'envía', 'recibir', 'recibe', 'pagar', 'paga',
    'esperar', 'espera', 'necesitar', 'necesita', 'intentar', 'intenta',
    'fracasar', 'fracasa', 'ganar', 'gana', 'perder', 'pierde',
    'jugar', 'juega', 'cantar', 'canta', 'bailar', 'baila', 'cocinar', 'cocina',
    'limpiar', 'limpia', 'lavar', 'lava', 'conducir', 'conduce',
    'volar', 'vuela', 'nadar', 'nada', 'escalar', 'escala', 'caer', 'cae',
    'construir', 'construye', 'crear', 'crea', 'romper', 'rompe',
    'arreglar', 'arregla', 'cortar', 'corta', 'pintar', 'pinta',
    'dibujar', 'dibuja', 'empujar', 'empuja', 'jalar', 'jala',
    'llevar', 'lleva', 'lanzar', 'lanza', 'atrapar', 'atrapa',
    'golpear', 'golpea', 'saltar', 'salta', 'sentarse', 'sienta',
    'pararse', 'para', 'encontrar', 'encuentra', 'buscar', 'busca',
    'guardar', 'guarda', 'eliminar', 'elimina', 'descargar', 'descarga',
    'subir', 'sube', 'instalar', 'instala', 'actualizar', 'actualiza',
    'imprimir', 'imprime', 'escanear', 'escanea', 'copiar', 'copia',
    'pegar', 'pega', 'chatear', 'chatea', 'trabajar', 'trabaja',
    'estudiar', 'estudia', 'pensar', 'piensa', 'saber', 'sabe',
    'querer', 'quiere', 'dar', 'da', 'tomar', 'toma', 'ver', 've',
    'venir', 'viene', 'mirar', 'mira', 'hacer', 'hace', 'decir', 'dice',
    'gustar', 'gusta', 'usar', 'usa', 'ir', 'va', 'ser', 'estar'
];

export const ADJETIVOS_INGLES = [
    'good', 'bad', 'big', 'small', 'beautiful', 'ugly', 'hot', 'cold',
    'happy', 'sad', 'fast', 'slow', 'new', 'old', 'young', 'long',
    'high', 'low', 'different', 'important', 'great', 'same', 'able',
    'strong', 'possible', 'free', 'true', 'full', 'special', 'easy',
    'clear', 'recent', 'certain', 'open', 'red', 'difficult', 'available',
    'short', 'single', 'wrong', 'private', 'past', 'common', 'poor',
    'natural', 'similar', 'dead', 'ready', 'simple', 'left', 'right',
    'general', 'blue', 'dark', 'entire', 'close', 'legal', 'final',
    'main', 'green', 'nice', 'huge', 'popular', 'traditional', 'cultural',
    'clean', 'dirty', 'rich', 'poor', 'hungry', 'thirsty', 'tired',
    'sick', 'healthy', 'safe', 'dangerous', 'expensive', 'cheap',
    'interesting', 'boring', 'famous', 'intelligent', 'stupid'
];

export const ADJETIVOS_ESPANOL = [
    'bueno', 'malo', 'grande', 'pequeño', 'hermoso', 'feo', 'caliente', 'frío',
    'feliz', 'triste', 'rápido', 'lento', 'nuevo', 'viejo', 'joven', 'largo',
    'alto', 'bajo', 'diferente', 'importante', 'grandioso', 'mismo', 'capaz',
    'fuerte', 'posible', 'libre', 'verdadero', 'lleno', 'especial', 'fácil',
    'claro', 'reciente', 'cierto', 'abierto', 'rojo', 'difícil', 'disponible',
    'corto', 'soltero', 'equivocado', 'privado', 'pasado', 'común', 'pobre',
    'natural', 'similar', 'muerto', 'listo', 'simple', 'izquierda', 'derecha',
    'general', 'azul', 'oscuro', 'entero', 'cerca', 'legal', 'final',
    'principal', 'verde', 'agradable', 'enorme', 'popular', 'tradicional',
    'cultural', 'limpio', 'sucio', 'rico', 'hambriento', 'sediento', 'cansado',
    'enfermo', 'saludable', 'seguro', 'peligroso', 'caro', 'barato',
    'interesante', 'aburrido', 'famoso', 'inteligente', 'estúpido'
];

export const SUSTANTIVOS_INGLES = [
    'world', 'computer', 'book', 'house', 'car', 'dog', 'cat', 'food', 'water',
    'friend', 'family', 'school', 'teacher', 'student', 'love', 'man', 'woman',
    'child', 'country', 'city', 'state', 'company', 'system', 'program',
    'question', 'government', 'number', 'night', 'point', 'home', 'room',
    'mother', 'father', 'area', 'money', 'story', 'fact', 'month', 'study',
    'eye', 'job', 'word', 'business', 'side', 'kind', 'head', 'service',
    'hour', 'game', 'line', 'end', 'member', 'law', 'name', 'president',
    'team', 'minute', 'idea', 'body', 'information', 'parent', 'face',
    'level', 'office', 'door', 'health', 'person', 'art', 'war', 'history',
    'party', 'result', 'change', 'morning', 'reason', 'research', 'girl',
    'guy', 'moment', 'air', 'force', 'education', 'foot', 'boy', 'age',
    'policy', 'process', 'music', 'market', 'sense', 'nation', 'plan',
    'college', 'interest', 'death', 'experience', 'effect', 'class',
    'control', 'care', 'field', 'development', 'role', 'effort', 'rate',
    'sun', 'moon', 'star', 'tree', 'flower', 'river', 'mountain',
    'movie', 'song', 'video', 'photo', 'telephone', 'keyboard', 'mouse',
    'screen', 'internet', 'website', 'password', 'username', 'breakfast',
    'lunch', 'dinner', 'bread', 'rice', 'chicken', 'fish', 'meat',
    'fruit', 'vegetable', 'milk', 'coffee', 'tea', 'juice', 'sugar',
    'salt', 'pepper', 'soup', 'salad', 'cake', 'chocolate', 'pizza',
    'sandwich', 'doctor', 'nurse', 'hospital', 'police', 'firefighter',
    'kitchen', 'bathroom', 'bedroom', 'garden', 'window', 'table', 'chair',
    'bed', 'picture', 'newspaper', 'magazine', 'letter', 'email', 'message'
];

export const SUSTANTIVOS_ESPANOL = [
    'mundo', 'computadora', 'libro', 'casa', 'coche', 'perro', 'gato', 'comida',
    'agua', 'amigo', 'familia', 'escuela', 'profesor', 'estudiante', 'amor',
    'hombre', 'mujer', 'niño', 'país', 'ciudad', 'estado', 'compañía',
    'sistema', 'programa', 'pregunta', 'gobierno', 'número', 'noche',
    'punto', 'hogar', 'habitación', 'madre', 'padre', 'área', 'dinero',
    'historia', 'hecho', 'mes', 'estudio', 'ojo', 'trabajo', 'palabra',
    'negocio', 'lado', 'tipo', 'cabeza', 'servicio', 'hora', 'juego',
    'línea', 'final', 'miembro', 'ley', 'nombre', 'presidente', 'equipo',
    'minuto', 'idea', 'cuerpo', 'información', 'cara', 'nivel', 'oficina',
    'puerta', 'salud', 'persona', 'arte', 'guerra', 'fiesta', 'resultado',
    'cambio', 'razón', 'investigación', 'chica', 'chico', 'momento',
    'aire', 'fuerza', 'educación', 'pie', 'edad', 'política', 'proceso',
    'música', 'mercado', 'sentido', 'nación', 'plan', 'universidad',
    'interés', 'muerte', 'experiencia', 'efecto', 'clase', 'control',
    'cuidado', 'campo', 'desarrollo', 'papel', 'esfuerzo', 'tasa',
    'sol', 'luna', 'estrella', 'árbol', 'flor', 'río', 'montaña',
    'película', 'canción', 'video', 'foto', 'teléfono', 'teclado', 'ratón',
    'pantalla', 'internet', 'sitio web', 'contraseña', 'usuario',
    'desayuno', 'almuerzo', 'cena', 'pan', 'arroz', 'pollo', 'pescado',
    'carne', 'fruta', 'verdura', 'leche', 'café', 'té', 'jugo', 'azúcar',
    'sal', 'pimienta', 'sopa', 'ensalada', 'pastel', 'chocolate', 'pizza',
    'sándwich', 'doctor', 'enfermera', 'hospital', 'policía', 'bombero',
    'cocina', 'baño', 'dormitorio', 'jardín', 'ventana', 'mesa', 'silla',
    'cama', 'foto', 'periódico', 'revista', 'carta', 'correo', 'mensaje'
];

export const SIGNOS_PUNTUACION = ['.', ',', '!', '?', ';', ':'];